# Generated by Django 2.2.7 on 2019-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('factor_country', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('factor_address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('factor_phone', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('factor_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
    ]
