# Generated by Django 2.2.7 on 2019-11-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транстпорт', 'verbose_name_plural': 'Транспорты'},
        ),
        migrations.AddField(
            model_name='transport',
            name='client_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
