# Generated by Django 2.2.7 on 2019-11-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='nmb',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='count_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
